# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs cmake . to create build files
      - name: Run cmake .
        run: cmake .
      
      # Runs make to create executables
      - name: Run make
        run: make

      # Runs the test executable (returns 0 if all tests pass, 1 otherwise)
      - name: Run test executable
        run : ./test